default: &default
  username: postgres
  password: postgres
  host: localhost
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  database: almost_hackersdevelopment

 
test:
  <<: *default
  database: almost_hackers_test

production:
  <<: *default
  database: almost_hackers_production
  username: asta
  password: <%= ENV['almost_hackers_DATABASE_PASSWORD'] %>
